### ISSUE TITLE
Feat: Add an email sending test to the smtp-connector project

### ISSUE THREAD

**Issue by daniloctdev** [TheMukeshPatel/smtp-connector#11]
Hello, I am a developer who uses your smtp-connector project to send emails from a WP Application. I noticed that the project does not have an email sending test, which would be useful to check the functioning of the connector and the correct formatting of the emails. I kindly ask you to add an email sending test to the project. Thank you for your work and your availability.

**Comment by TheMukeshPatel** [comment]
Thanks for your suggestion.

**Comment by TheMukeshPatel** [comment]
Update: Thanks for your suggestion. SMTP Email testing facility is added in version 1.2.0.
