### ISSUE TITLE
Gmail moving to Oauth

### ISSUE THREAD

**Issue by quadcom** [TheMukeshPatel/smtp-connector#2]
Just thought I would let you know that Gmail is moving off from simple SMTP auth to OAuth at the end of 2024. You might want to look into adding OAuth support, or you could lose a big integration soon.

https://support.google.com/a/answer/14114704?hl=en

**Comment by TheMukeshPatel** [comment]
Thanks for the update. But we can still use the App Password!

**Comment by quadcom** [comment]
That is getting phased out for Workspace clients in two phases starting
June 15th and ending Sept 30th

https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html
